[project]
name = "pytest-testops"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.0.0",
]

[project.entry-points.pytest11]
testops = "pytest_testops.plugin"

[build-system]
requires = ["uv_build>=0.11.26,<0.12"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "demo-project/demo-algorithms",
]
